[package]
name = "vsomeip_compat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tempfile = "3"
vsomeip-rs = {path = "../vsomeip-rs"}
serde_json = "1"
netdev = "0.25"

[dev-dependencies]