[package]
name = "smip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"

members = ["smip_core"]


[dependencies]
smip_core = { path = "smip_core" }