name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:38

    steps:
    - name: Setup cmake
      run: sudo dnf -y install cmake 
    - name: Install dependencies
      run: sudo dnf -y install make git clang boost-devel nodejs

    - name: Install latest stable Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          
    - name: Install vsomeip
      run: |
           git clone https://github.com/COVESA/vsomeip
           cd vsomeip
           git checkout cf497232adf84f55947f7a24e1b64e04b49f1f38
           mkdir build
           cd build
           # https://github.com/COVESA/vsomeip/issues/688
           # https://github.com/COVESA/vsomeip/issues/527
           cmake -E env CXXFLAGS="-Wno-error=stringop-overflow" cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Debug
           make -j
           sudo make install
           cd ../..

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --workspace --all-features --verbose
    - name: Run tests
      run: cargo test --workspace --all-features --verbose
